name: wr-mass-estimates

channels:
  - conda-forge

dependencies:
  - python
  - numpy
  - scipy
  - astropy
  - matplotlib
  - seaborn
  - lmfit
  - tensorflow
  - pandas
  - ultranest
  - numba
  - sklearn
